import { areas } from "@/i18n/dict";

export type StationArea = (typeof areas)[number];

export type KnownStation = {
  id: string;
  name: string;
  location: string;
  area: StationArea;
  lat: number;
  lng: number;
  services?: string[];
  contact?: string;
  specialty?: string;
  aliases?: string[];
  source: "official" | "community";
};

export const knownStations: KnownStation[] = [
  {
    id: "binimoy-filling-station",
    name: "Binimoy Filling Station",
    location: "Mostofee, Lalmonirhat-Aditmari Road, Lalmonirhat Sadar",
    area: "Lalmonirhat Sadar",
    lat: 25.9061326,
    lng: 89.4334891,
    services: ["Octane", "Petrol", "Diesel", "Car Wash", "Propane Exchange"],
    contact: "+880 591-61376",
    specialty: "Open 24 hours, near Mostofee Bazar",
    aliases: ["Mostofee Bazar", "Mostafee", "Binimoy Prime"],
    source: "community",
  },
  {
    id: "hossain-brothers-filling-station",
    name: "Hossain Brothers Filling Station",
    location: "Airport Road, Mahendranagar / Haribhange, Lalmonirhat Sadar",
    area: "Lalmonirhat Sadar",
    lat: 25.8991583,
    lng: 89.4321803,
    services: ["Octane", "Petrol", "Diesel", "Car Wash", "Air Pump"],
    contact: "+880 1824-619578",
    specialty: "Long-standing trusted station in Mahendranagar",
    aliases: ["M/S Hossain Brothers F/S", "Haribhange", "Airport Road"],
    source: "official",
  },
  {
    id: "limon-brothers-filling-station",
    name: "Messrs Limon & Brothers Filling Station",
    location: "N509, Mahendranagar, Lalmonirhat Sadar",
    area: "Lalmonirhat Sadar",
    lat: 25.8784479,
    lng: 89.4468794,
    services: ["Octane", "Petrol", "Diesel"],
    specialty: "Registered dealer under Padma Oil",
    aliases: ["M/S Limon & Brothers Filling Station", "Limon Brothers", "Limon Filling Station"],
    source: "official",
  },
  {
    id: "gm-trading-filling-station",
    name: "M/S G.M. Trading Filling Station",
    location: "Saptana, Lalmonirhat-Phulbari Road, Lalmonirhat Sadar",
    area: "Lalmonirhat Sadar",
    lat: 25.9227451,
    lng: 89.480016,
    specialty: "Officially listed filling station in Sadar area",
    aliases: ["GM Trading", "G.M.Trading", "G.M Treading", "Saptana"],
    source: "official",
  },
  {
    id: "shaheen-brothers-filling-station",
    name: "Shaheen & Brothers Filling Station",
    location: "Barobarihat, Lalmonirhat Sadar",
    area: "Lalmonirhat Sadar",
    lat: 25.8691109,
    lng: 89.5088308,
    specialty: "Officially listed station on the Barobarihat side",
    aliases: ["Shaheen Brothers", "Barobarihat"],
    source: "official",
  },
  {
    id: "fatema-filling-station",
    name: "Fatema Filling Station",
    location: "Aditmari town approach, near Sadar border",
    area: "Aditmari",
    lat: 25.9139652,
    lng: 89.3599127,
    services: ["Petrol", "Diesel"],
    specialty: "Frequently used by travelers from Sadar to Aditmari",
    aliases: ["Fatima Filling Station", "Aditmari"],
    source: "official",
  },
  {
    id: "daulah-filling-station",
    name: "Messrs Daulah Filling Station",
    location: "Lalmonirhat-Phulbari Road, Saptibari / Khatapara, Aditmari",
    area: "Aditmari",
    lat: 25.905422,
    lng: 89.4104487,
    services: ["Petrol", "Diesel", "Lubricants"],
    contact: "+880 1780-801121",
    specialty: "Main station for Saptibari residents",
    aliases: ["Doula Filling Station", "Daulah", "Saptibari", "Khatapara"],
    source: "community",
  },
  {
    id: "ks-filling-station",
    name: "Messrs K.S. Filling Station",
    location: "Madanpur, Namurirhat, Aditmari",
    area: "Aditmari",
    lat: 25.9235,
    lng: 89.3111,
    services: ["Octane", "Petrol", "Diesel", "Restroom", "WiFi"],
    contact: "+880 1787-790693",
    specialty: "Highway facility with modern amenities; coordinate seeded near Madanpur/Namurirhat",
    aliases: ["K.S. Filling Station", "Namuri Bazar", "Namurirhat", "Madanpur"],
    source: "official",
  },
  {
    id: "rawshan-filling-station",
    name: "Rawshan Filling Station",
    location: "Tushbhandar, Kaliganj",
    area: "Kaliganj",
    lat: 25.9665895,
    lng: 89.2288866,
    specialty: "Officially listed filling station in Tushbhandar",
    aliases: ["Rawshan", "Tushbhandar"],
    source: "official",
  },
  {
    id: "jamena-filling-station",
    name: "Jamena Filling Station",
    location: "Chaparhat, Kaliganj",
    area: "Kaliganj",
    lat: 26.0017735,
    lng: 89.2708384,
    specialty: "Officially listed filling station in Chaparhat",
    aliases: ["Jameena", "Chaparhat"],
    source: "official",
  },
  {
    id: "fazle-rabbe-filling-station",
    name: "Fazle Rabbe Filling Station",
    location: "Rudreshwar, Kakina, Kaliganj",
    area: "Kaliganj",
    lat: 25.9167,
    lng: 89.2833,
    specialty: "Officially listed filling station near Kakina; coordinate seeded near Rudreshwar",
    aliases: ["Rudreshwar", "Kakina"],
    source: "official",
  },
  {
    id: "kabbo-digonto-filling-station",
    name: "M/S Kabbo Digonto Filling Station",
    location: "Kashiram / Tushbhandar corridor, Kaliganj",
    area: "Kaliganj",
    lat: 25.9695412,
    lng: 89.200207,
    specialty: "Officially listed filling station in Kashiram",
    aliases: ["Kabbo Digonto", "Kabbo Diganto", "Kashiram"],
    source: "official",
  },
  {
    id: "akash-filling-station",
    name: "Akash Filling Station",
    location: "Lalmonirhat to Burimari Road, Tushbhandar / Kakina side, Kaliganj",
    area: "Kaliganj",
    lat: 25.9314335,
    lng: 89.254615,
    specialty: "Community-mapped station on the Kakina side corridor",
    aliases: ["Akash", "Kakina side", "Tushbhandar road"],
    source: "community",
  },
  {
    id: "hatibandha-filling-station",
    name: "Hatibandha Filling Station",
    location: "Lalmonirhat-Patgram Highway, Hatibandha",
    area: "Hatibandha",
    lat: 26.1237264,
    lng: 89.1427952,
    specialty: "Community-mapped station on the Hatibandha highway stretch",
    aliases: ["Hatibandha", "Hatibandhar Filling Station"],
    source: "community",
  },
  {
    id: "ds-filling-station",
    name: "M/S D S Filling Station",
    location: "North Holdibari / Sindurna, Hatibandha",
    area: "Hatibandha",
    lat: 26.1047231,
    lng: 89.1415102,
    specialty: "Government-registered filling station in Hatibandha",
    aliases: ["D S Filling Station", "DS Filling Station", "Sindurna", "North Holdibari"],
    source: "official",
  },
  {
    id: "mortuza-filling-station",
    name: "Mortuza Filling Station",
    location: "Lalmonirhat-Patgram Highway, Patikapara, Hatibandha",
    area: "Hatibandha",
    lat: 26.0294371,
    lng: 89.1612028,
    specialty: "Community-mapped station on the Patikapara stretch",
    aliases: ["Mortuza", "Patikapara"],
    source: "community",
  },
  {
    id: "alhaj-jm-filling-station",
    name: "Alhaj J.M. Filling Station",
    location: "Ufarmara, Burimari, Patgram",
    area: "Patgram",
    lat: 26.3942,
    lng: 88.9406,
    specialty: "Officially listed station serving the Burimari corridor; coordinate seeded near Ufarmara/Burimari",
    aliases: ["Alhaj JM", "Burimari", "Ufarmara"],
    source: "official",
  },
  {
    id: "sharmila-filling-station",
    name: "M/S Sharmila Filling Station",
    location: "Rasulgonj, Patgram Pourashava",
    area: "Patgram",
    lat: 26.33625,
    lng: 89.02654,
    specialty: "Officially listed filling station in Patgram town side; coordinate seeded near Rasulgonj",
    aliases: ["Sharmila", "Rasulgonj", "Rasulganj"],
    source: "official",
  },
  {
    id: "patgram-filling-station",
    name: "Patgram Filling Station",
    location: "Patgram town, Patgram",
    area: "Patgram",
    lat: 26.3402149,
    lng: 89.0246927,
    specialty: "Community-mapped station in Patgram town",
    aliases: ["Patgram town pump", "Patgram town"],
    source: "community",
  },
];
